### ISSUE TITLE
I downloaded the windows version, but after selecting the image, clicking on the OPEN button doesn't work

### ISSUE THREAD

**Issue by pipivv** [Nyre221/VoxelMaterials#1]

**Comment by Nyre221** [comment]
Hi, thanks for reporting the problem.

1) write down all the steps to reproduce the issue.
2) what version of windows are you using?
3) can you upload the color palette you are using to github?

**Comment by pipivv** [comment]
Thanks for your quick reply, I downloaded "VoxelMaterial_windows.tar.gz" from "https://nyre221.itch.io/voxelmaterials"
.After unzipping and running the program, clicking on OPEN the program does not respond.（The program didn't crash, just couldn't proceed to the next step）
![131231](https://github.com/Nyre221/VoxelMaterials/assets/33804268/dee0cac9-69b5-4523-94ac-6583f4ea8f87)
I've run it on 3 computers with different hardware and systems (win10 & win11) and all of them don't respond after clicking OPEN.

**Comment by Nyre221** [comment]
I tried on a laptop (win 10) with this color palette and it works: 
![atari2600_palette](https://github.com/Nyre221/VoxelMaterials/assets/104171042/ce44eb69-98dd-4eca-bf40-923d96bb8eb1)

Remember that this program requires color palettes to work (256x1 pixels)

Could you send me the image you are using or try with the one I used?
https://github.com/mattperrin/MagicaVoxelPalettes/blob/master/atari2600_palette.png

edit:
I want to add that after pressing "OPEN" nothing happens because the program probably refuses to load the image (as if it were the wrong size or format).

**Comment by pipivv** [comment]
Thanks for the reply, it was my problem, I used the wrong image for the test, using your color palette is fine.

**Comment by Nyre221** [comment]
Happy to help :)
